services:
  - type: web
    name: discord-email-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start_bot.py
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
