services:
  - type: web
    name: discord-email-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start_bot.py
    healthCheckPath: /health
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: PORT
        value: 10000
